version: '3.7'

services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5433:5433'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=igniteprisma
      - PGPORT=5433
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: api
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
